# Generated by Django 5.0.2 on 2025-04-04 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0005_category_image_alter_produto_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='variacao',
            name='cor',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='variacao',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='variacoes/'),
        ),
        migrations.AddField(
            model_name='variacao',
            name='tamanho',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='variacao',
            name='estoque',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
